// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwPTTW0BxZRiEic9urrRSKWMdgJm55bq8',
    appId: '1:366595702924:web:0e2a71a67c1c1d17163ba9',
    messagingSenderId: '366595702924',
    projectId: 'chatapp-b1cc4',
    authDomain: 'chatapp-b1cc4.firebaseapp.com',
    databaseURL: 'https://chatapp-b1cc4-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-b1cc4.firebasestorage.app',
    measurementId: 'G-ZNHVH3BG8S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOPmKHSUw02rW9nF2jiwCunpIVjGb0V0M',
    appId: '1:366595702924:android:6e37a54329675fbb163ba9',
    messagingSenderId: '366595702924',
    projectId: 'chatapp-b1cc4',
    databaseURL: 'https://chatapp-b1cc4-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-b1cc4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDj8ODYXLD6Sec-1uWqWRhQ6Qt2pbZKEYk',
    appId: '1:366595702924:ios:0259bbbe4c27e2b7163ba9',
    messagingSenderId: '366595702924',
    projectId: 'chatapp-b1cc4',
    databaseURL: 'https://chatapp-b1cc4-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-b1cc4.firebasestorage.app',
    iosBundleId: 'com.example.chatappLight',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDj8ODYXLD6Sec-1uWqWRhQ6Qt2pbZKEYk',
    appId: '1:366595702924:ios:0259bbbe4c27e2b7163ba9',
    messagingSenderId: '366595702924',
    projectId: 'chatapp-b1cc4',
    databaseURL: 'https://chatapp-b1cc4-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-b1cc4.firebasestorage.app',
    iosBundleId: 'com.example.chatappLight',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwPTTW0BxZRiEic9urrRSKWMdgJm55bq8',
    appId: '1:366595702924:web:cfe7a1b3bf1c2868163ba9',
    messagingSenderId: '366595702924',
    projectId: 'chatapp-b1cc4',
    authDomain: 'chatapp-b1cc4.firebaseapp.com',
    databaseURL: 'https://chatapp-b1cc4-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-b1cc4.firebasestorage.app',
    measurementId: 'G-YQ3ZWNH98N',
  );
}
